### ISSUE TITLE
API para efetuar uma nova cobrança de produto

### ISSUE THREAD

**Issue by heitoradao** [iugu-for-devs/iugu-lite#11]
Eu como usuario gostaria de efutar uma nova cobrança avulsa de um produto especifico.
Cada cobrança deve receber:
- Token da empresa
- Token do meio de pagamento
- Token do produto envolvido

Cada solicitação deve possuir apenas 1 token de cada (ou seja, apenas 1 item pode ser cobrado por solicitação)

Cada cobrança emitida deve gerar um token alfanumérico único de 20 caracteres e o status
inicial da cobrança é pendente.

**Comment by J-Costa** [comment]
- Adicionar data de vencimento
- valor com base na fatura

**Comment by J-Costa** [comment]
Mergeado no #44, fechando esse card e issue
closes #42
