### ISSUE TITLE
Area de acesso do empreendedor

### ISSUE THREAD

**Issue by heitoradao** [iugu-for-devs/iugu-lite#16]
Eu como cliente da iugu-lite, quero cadastrar contas, configurar dados da minha empresa, consultar informações gerenciais como extratos de cobranças realizadas.

**Comment by joaorsalmeida** [comment]
Legal a ideia de ter uma `Area do Empreendedor` que unifica o acesso às funcionalidades, mas me parece que cada funcionalidade aqui poderia ser feita de forma separada (e com isso ter cards separados):

- Configurar dados da minha empresa
- Consultar extratos de cobranças realizadas
- Cadastrar as contas/meios de pagamento que desejo utiliziar efetivamente

**Comment by gabrielsugai** [comment]
> Legal a ideia de ter uma `Area do Empreendedor` que unifica o acesso às funcionalidades, mas me parece que cada funcionalidade aqui poderia ser feita de forma separada (e com isso ter cards separados):
> 
> * Configurar dados da minha empresa
> * Consultar extratos de cobranças realizadas
> * Cadastrar as contas/meios de pagamento que desejo utiliziar efetivamente

Vou dividir em 3 cards, e esse card sera o painel com a configuraçao de dados da empresa
