### ISSUE TITLE
Gerir meios de pagamento (Plataforma Iugu-Lite)

### ISSUE THREAD

**Issue by heitoradao** [iugu-for-devs/iugu-lite#3]
Eu como Administrador da plataforma, devo conseguir criar um meio de pagamento, seja ele boleto, pix e/ou cartão de credito. Inserindo as seguintes informações:

- Nome
- Icone
- Taxa de cobrança %
- Taxa máxima em R$

**Comment by joaorsalmeida** [comment]
Ativar/Desativar meios de pagamento pode ser uma tarefa separada. A princípio, pensando em entrega de valor, dificilmente vamos começar cadastrando meios de pagamento que não serão utilizados ;)
