### ISSUE TITLE
Empreendedor Gere Produtos

### ISSUE THREAD

**Issue by heitoradao** [iugu-for-devs/iugu-lite#4]
Eu como Empreendedor, quero:
- [x] gerenciar produtos que vou vender para meus clientes (CRUD).
- [x] obter token de cada produto.

**Comment by HenriqueMorato** [comment]
Acho que API poderia ficar pra outro card senão esse card vai ficar um pouco grande demais.

**Comment by joaorsalmeida** [comment]
Concordo com o comentário do @HenriqueMorato . Escrevam como User Stories que vão notar que fica muito grande fazer tudo de uma vez. Podemos ter uma tarefa para a gestão dos produtos dentro da app e outra para permitir as mudanças via API.

**Comment by andre-dan** [comment]
@joaorsalmeida que vc e henrique está falando de dividir esse card, ficando um para gestão do recurso produto, e outro card com a API de obtenção de token é isso?
