### ISSUE TITLE
Criar um token para representar Purchasers

### ISSUE THREAD

**Issue by heitoradao** [iugu-for-devs/iugu-lite#6]
Ao cadastrar uma empresa, os usuários dessa empresa terão acesso a um token único alfanumérico de 20 caracteres que será utilizado para integração com a API de pagamentos.

**Comment by joaorsalmeida** [comment]
A descrição dessa tarefa me parece ser a da #9

**Comment by joaorsalmeida** [comment]
Aproveitando, senti falta de ter uma tarefa priorizada para receber dados dos clientes finais dos empreendedores e gerar um token para estes clientes. Sem isso não vai ser possível realizar uma venda ;)
